objc_library(
    name = "App",
    srcs = ["App.m"],
    hdrs = ["App.h"],
    visibility = ["//visibility:public"],
    includes = ["."],
    sdk_frameworks = [
        "AppKit",
        "Foundation",
    ],
)