objc_library(
    name = "ChatInput",
    srcs = ["ChatInput.m"],
    hdrs = ["ChatInput.h"],
    visibility = ["//visibility:public"],
    includes = ["."],
    sdk_frameworks = [
        "AppKit",
        "Foundation",
    ],
)