objc_library(
    name = "Networking",
    srcs = ["Networking.m"],
    hdrs = ["Networking.h"],
    visibility = ["//visibility:public"],
    includes = ["."],
    sdk_frameworks = [
        "AppKit",
        "Foundation",
    ],
)