objc_library(
    name = "Keychain",
    srcs = ["Keychain.m"],
    hdrs = ["Keychain.h"],
    includes = ["."],
    sdk_frameworks = [
        "Cocoa",
        "Security",
    ],
    visibility = ["//visibility:public"],
)