objc_library(
    name = "HistoryTable",
    srcs = ["HistoryTable.m"],
    hdrs = ["HistoryTable.h"],
    visibility = ["//visibility:public"],
    includes = ["."],
    sdk_frameworks = [
        "AppKit",
        "Foundation",
    ],
)