objc_library(
    name = "HistoryTable",
    srcs = ["HistoryTable.m"],
    hdrs = ["HistoryTable.h"],
    visibility = ["//visibility:public"],
    includes = ["."],
    sdk_frameworks = [
        "AppKit",
        "Foundation",
    ],
    copts = [
        "-fno-objc-arc",
        "-mmacosx-version-min=10.4",
    ],
)