objc_library(
    name = "Settings",
    srcs = ["Settings.m"],
    hdrs = ["Settings.h"],
    visibility = ["//visibility:public"],
    includes = ["."],
    sdk_frameworks = [
        "AppKit",
        "Foundation",
        "Security",
    ],
    copts = [
        "-fno-objc-arc",
        "-mmacosx-version-min=10.4",
    ],
)